export const CATEGORIES = {
  'student-graduate': {
    id: 'student-graduate',
    label: 'Student / Graduate',
    bestFor: 'Students, recent graduates, interns, apprentices, and early-career applicants.',
    defaultStructure: 'combination',
    recommendedTone: 'clear, energetic, credible, and not overclaimed',
    sectionOrder: ['profile', 'education', 'skills', 'projects', 'experience', 'certifications', 'languages', 'volunteering'],
    requiredSections: ['profile', 'education', 'skills'],
    optionalSections: ['projects', 'internships', 'partTimeWork', 'volunteering', 'certifications', 'languages'],
    priority: ['education', 'projects', 'transferableSkills'],
    commonMistakes: [
      'Trying to look senior when the evidence is early-career.',
      'Leaving out part-time work, volunteering, or projects that prove reliability.',
      'Using vague claims such as hard-working without evidence.',
    ],
    aiOpportunities: ['career-story-to-cv', 'project-bullet-builder', 'summary-writer', 'cover-letter-starter'],
    templateRecommendation: 'clean-student',
  },
  professional: {
    id: 'professional',
    label: 'General Professional',
    bestFor: 'Most office, administrative, operations, project, management, and skilled professional roles.',
    defaultStructure: 'reverse-chronological',
    recommendedTone: 'professional, specific, outcome-led',
    sectionOrder: ['profile', 'skills', 'experience', 'education', 'certifications', 'projects', 'languages'],
    requiredSections: ['profile', 'skills', 'experience', 'education'],
    optionalSections: ['certifications', 'projects', 'languages', 'professionalMemberships'],
    priority: ['recentExperience', 'achievements', 'roleFit'],
    commonMistakes: [
      'Listing duties without outcomes.',
      'Using a generic profile that could fit anyone.',
      'Hiding the most relevant recent experience too low.',
    ],
    aiOpportunities: ['bullet-sharpener', 'job-tailoring', 'summary-writer', 'cover-letter-personaliser'],
    templateRecommendation: 'clean-modern',
  },
  tech: {
    id: 'tech',
    label: 'Tech / IT / Data',
    bestFor: 'Developers, IT support, data analysts, cybersecurity, product, cloud, systems, and digital roles.',
    defaultStructure: 'combination',
    recommendedTone: 'technical but buyer-readable',
    sectionOrder: ['profile', 'technicalSkills', 'projects', 'experience', 'education', 'certifications', 'portfolio'],
    requiredSections: ['profile', 'technicalSkills', 'experience'],
    optionalSections: ['projects', 'github', 'portfolio', 'certifications', 'publications'],
    priority: ['technicalSkills', 'evidenceOfDelivery', 'tools', 'projects'],
    commonMistakes: [
      'Dumping every tool without showing practical use.',
      'Making the CV unreadable to non-technical recruiters.',
      'Leaving out links to portfolio, GitHub, or deployed work where relevant.',
    ],
    aiOpportunities: ['technical-bullet-sharpener', 'project-translator', 'job-tailoring', 'skills-gap-check'],
    templateRecommendation: 'tech-ats',
  },
  creative: {
    id: 'creative',
    label: 'Creative / Design / Media',
    bestFor: 'Designers, writers, marketers, content creators, media, UX, and creative professionals.',
    defaultStructure: 'combination',
    recommendedTone: 'polished, confident, portfolio-led',
    sectionOrder: ['profile', 'portfolio', 'skills', 'selectedProjects', 'experience', 'education', 'awards'],
    requiredSections: ['profile', 'portfolio', 'skills', 'experience'],
    optionalSections: ['selectedProjects', 'awards', 'clients', 'publications', 'certifications'],
    priority: ['portfolio', 'selectedWork', 'impact', 'creativeTools'],
    commonMistakes: [
      'Using a beautiful layout that fails ATS parsing.',
      'Describing creativity without showing outcomes or portfolio proof.',
      'Making the CV too visual when the employer needs scanability.',
    ],
    aiOpportunities: ['portfolio-summary', 'creative-project-bullets', 'tone-polish', 'job-tailoring'],
    templateRecommendation: 'creative-ats-safe',
  },
  healthcare: {
    id: 'healthcare',
    label: 'Healthcare / Care / Clinical',
    bestFor: 'Nurses, care assistants, healthcare assistants, allied health, clinical admin, and regulated care roles.',
    defaultStructure: 'reverse-chronological',
    recommendedTone: 'clear, compliant, safe, and evidence-led',
    sectionOrder: ['profile', 'licensesCertifications', 'clinicalSkills', 'experience', 'education', 'training', 'languages'],
    requiredSections: ['profile', 'licensesCertifications', 'clinicalSkills', 'experience'],
    optionalSections: ['training', 'specialisms', 'professionalMemberships', 'languages'],
    priority: ['registration', 'certifications', 'clinicalExperience', 'safeguarding', 'compliance'],
    commonMistakes: [
      'Burying licence or registration details too low.',
      'Using informal job titles instead of recognised healthcare terminology.',
      'Leaving out safeguarding, confidentiality, infection control, or patient-safety experience.',
    ],
    aiOpportunities: ['clinical-bullet-sharpener', 'compliance-language', 'summary-writer', 'interview-prep'],
    templateRecommendation: 'healthcare-clear',
  },
  'trades-hospitality-retail': {
    id: 'trades-hospitality-retail',
    label: 'Trades / Hospitality / Retail',
    bestFor: 'Retail, hospitality, warehouse, delivery, construction, trades, service, and practical frontline roles.',
    defaultStructure: 'reverse-chronological',
    recommendedTone: 'direct, practical, reliable, and skills-led',
    sectionOrder: ['profile', 'coreSkills', 'certificationsTickets', 'experience', 'education', 'availability', 'languages'],
    requiredSections: ['profile', 'coreSkills', 'experience'],
    optionalSections: ['certificationsTickets', 'availability', 'licences', 'languages', 'references'],
    priority: ['reliability', 'availability', 'practicalSkills', 'safety', 'customerService'],
    commonMistakes: [
      'Underselling practical work as just basic duties.',
      'Leaving out tickets, licences, shifts, safety training, or equipment experience.',
      'Using long paragraphs instead of quick proof points.',
    ],
    aiOpportunities: ['plain-work-to-cv', 'reliability-bullets', 'customer-service-bullets', 'short-summary'],
    templateRecommendation: 'simple-direct',
  },
  executive: {
    id: 'executive',
    label: 'Executive / Senior',
    bestFor: 'Senior managers, directors, heads of function, founders, consultants, and leadership roles.',
    defaultStructure: 'achievement-led-chronological',
    recommendedTone: 'strategic, measured, board-ready',
    sectionOrder: ['executiveProfile', 'leadershipHighlights', 'experience', 'boardAdvisory', 'education', 'certifications', 'publications'],
    requiredSections: ['executiveProfile', 'leadershipHighlights', 'experience'],
    optionalSections: ['boardAdvisory', 'publications', 'speaking', 'professionalMemberships'],
    priority: ['scale', 'leadershipImpact', 'commercialResults', 'transformation', 'governance'],
    commonMistakes: [
      'Listing responsibilities instead of scale and outcomes.',
      'Making the CV too operational for a leadership role.',
      'Using inflated language without numbers or proof.',
    ],
    aiOpportunities: ['executive-summary', 'impact-bullet-builder', 'board-tone-polish', 'job-tailoring'],
    templateRecommendation: 'executive-clean',
  },
  academic: {
    id: 'academic',
    label: 'Academic / Research',
    bestFor: 'Researchers, lecturers, PhD candidates, postdocs, research administrators, and academic grant roles.',
    defaultStructure: 'academic-cv',
    recommendedTone: 'precise, evidence-heavy, publication-aware',
    sectionOrder: ['researchProfile', 'education', 'appointments', 'publications', 'grants', 'teaching', 'researchProjects', 'conferences', 'skills', 'service'],
    requiredSections: ['researchProfile', 'education', 'appointments'],
    optionalSections: ['publications', 'grants', 'teaching', 'conferences', 'ethics', 'methods', 'orcid'],
    priority: ['researchFit', 'publications', 'grants', 'methods', 'teaching', 'ethics'],
    commonMistakes: [
      'Forcing an academic CV into a short corporate template.',
      'Hiding publications, grants, or methods expertise.',
      'Using corporate achievement language where academic evidence is expected.',
    ],
    aiOpportunities: ['research-profile', 'methods-summary', 'academic-cover-letter', 'grant-fit-review'],
    templateRecommendation: 'academic-structured',
  },
  'career-changer': {
    id: 'career-changer',
    label: 'Career Changer',
    bestFor: 'People moving into a new field, returning after a break, or translating experience from another sector.',
    defaultStructure: 'hybrid',
    recommendedTone: 'transferable, honest, confident, and focused',
    sectionOrder: ['profile', 'transferableSkills', 'selectedAchievements', 'experience', 'education', 'certifications', 'projects'],
    requiredSections: ['profile', 'transferableSkills', 'experience'],
    optionalSections: ['selectedAchievements', 'projects', 'training', 'volunteering'],
    priority: ['transferableSkills', 'careerLogic', 'evidence', 'learning', 'roleFit'],
    commonMistakes: [
      'Apologising for the career change instead of explaining the value.',
      'Using a functional CV that hides chronology too aggressively.',
      'Failing to connect past experience to the target job.',
    ],
    aiOpportunities: ['career-story-translator', 'transferable-skills-map', 'summary-writer', 'cover-letter-bridge'],
    templateRecommendation: 'hybrid-transition',
  },
};

export const CATEGORY_OPTIONS = Object.values(CATEGORIES).map(({ id, label, bestFor }) => ({
  id,
  label,
  bestFor,
}));

export function getCategory(categoryId = 'professional') {
  return CATEGORIES[categoryId] || CATEGORIES.professional;
}
