export const REGIONS = {
  'uk-ireland': {
    id: 'uk-ireland',
    label: 'UK & Ireland',
    documentName: 'CV',
    paperSize: 'A4',
    spelling: 'british',
    idealPages: 2,
    maxPages: 2,
    dateFormat: 'Sep 2024',
    defaultStructure: 'reverse-chronological',
    summaryLabel: 'Personal Profile',
    photo: 'discouraged',
    personalInfo: {
      dateOfBirth: 'discouraged',
      nationality: 'discouraged',
      maritalStatus: 'discouraged',
      visaStatus: 'not-usual',
      fullAddress: 'not-required',
    },
    referencesStyle: 'available-on-request',
    warnings: [
      'Do not add a photo for most UK or Irish applications.',
      'Avoid date of birth, marital status, and nationality unless specifically required.',
      'Keep most professional CVs to two pages or fewer.',
      'Use British spelling such as organised, programme, and centre.',
    ],
    notes: [
      'Use CV, not resume.',
      'Open with a short personal profile.',
      'Most recent experience should appear first.',
    ],
  },
  us: {
    id: 'us',
    label: 'United States',
    documentName: 'Resume',
    paperSize: 'Letter',
    spelling: 'american',
    idealPages: 1,
    maxPages: 2,
    dateFormat: 'Sep 2024',
    defaultStructure: 'reverse-chronological',
    summaryLabel: 'Professional Summary',
    photo: 'never',
    personalInfo: {
      dateOfBirth: 'never',
      nationality: 'never',
      maritalStatus: 'never',
      visaStatus: 'only-if-relevant',
      fullAddress: 'not-required',
    },
    referencesStyle: 'omit',
    warnings: [
      'Do not add a photo to a US resume.',
      'Do not include date of birth, marital status, or nationality.',
      'Use American spelling such as organized, program, and center.',
      'References are normally omitted from the resume.',
    ],
    notes: [
      'Use Resume, not CV, except for academic or medical contexts.',
      'One page is preferred for early career; two pages is acceptable for experienced candidates.',
    ],
  },
  'germany-dach': {
    id: 'germany-dach',
    label: 'Germany / DACH',
    documentName: 'Lebenslauf',
    paperSize: 'A4',
    spelling: 'localised',
    idealPages: 2,
    maxPages: 3,
    dateFormat: '09/2024',
    defaultStructure: 'reverse-chronological',
    summaryLabel: 'Profile',
    photo: 'often-expected',
    personalInfo: {
      dateOfBirth: 'common',
      nationality: 'common',
      maritalStatus: 'optional',
      visaStatus: 'useful-if-relevant',
      fullAddress: 'common',
    },
    referencesStyle: 'omit-or-on-request',
    warnings: [
      'A professional photo is still common in DACH markets, but should be optional and context-led.',
      'Keep the structure formal and easy to scan.',
      'Use clear dates and avoid unexplained gaps where possible.',
    ],
    notes: [
      'A structured Lebenslauf is expected.',
      'Certificates, training, and language levels matter.',
    ],
  },
  france: {
    id: 'france',
    label: 'France',
    documentName: 'CV',
    paperSize: 'A4',
    spelling: 'localised',
    idealPages: 1,
    maxPages: 2,
    dateFormat: '09/2024',
    defaultStructure: 'reverse-chronological',
    summaryLabel: 'Profil',
    photo: 'optional-common',
    personalInfo: {
      dateOfBirth: 'optional',
      nationality: 'optional',
      maritalStatus: 'discouraged',
      visaStatus: 'useful-if-relevant',
      fullAddress: 'optional',
    },
    referencesStyle: 'omit',
    warnings: [
      'Keep the CV concise; one page is common, two pages for more experience.',
      'Do not overcrowd the page with design elements that hurt ATS parsing.',
    ],
    notes: [
      'Photo use is common in some contexts but should remain optional.',
      'Language levels should be clear and credible.',
    ],
  },
  'netherlands-scandinavia': {
    id: 'netherlands-scandinavia',
    label: 'Netherlands / Scandinavia',
    documentName: 'CV',
    paperSize: 'A4',
    spelling: 'international-english',
    idealPages: 1,
    maxPages: 2,
    dateFormat: 'Sep 2024',
    defaultStructure: 'reverse-chronological',
    summaryLabel: 'Profile',
    photo: 'optional',
    personalInfo: {
      dateOfBirth: 'optional-discouraged',
      nationality: 'optional',
      maritalStatus: 'discouraged',
      visaStatus: 'useful-if-relevant',
      fullAddress: 'not-required',
    },
    referencesStyle: 'omit-or-on-request',
    warnings: [
      'Keep the CV direct, clean, and evidence-led.',
      'Avoid excessive personal details unless the employer clearly asks for them.',
    ],
    notes: [
      'English CVs are acceptable in many international roles.',
      'A concise profile and clear skills section work well.',
    ],
  },
  europass: {
    id: 'europass',
    label: 'Europass / EU Institutions',
    documentName: 'Europass CV',
    paperSize: 'A4',
    spelling: 'british-or-international',
    idealPages: 2,
    maxPages: 4,
    dateFormat: 'Sep 2024',
    defaultStructure: 'structured-europass',
    summaryLabel: 'About me',
    photo: 'optional',
    personalInfo: {
      dateOfBirth: 'optional',
      nationality: 'optional',
      maritalStatus: 'discouraged',
      visaStatus: 'useful-if-relevant',
      fullAddress: 'optional',
    },
    referencesStyle: 'on-request',
    warnings: [
      'Use Europass mainly when the employer, institution, or programme expects it.',
      'Do not use Europass automatically for every private-sector role.',
    ],
    notes: [
      'CEFR language levels are important.',
      'Useful for EU mobility, grants, public sector, and some academic contexts.',
    ],
  },
  'uae-gcc': {
    id: 'uae-gcc',
    label: 'UAE / GCC',
    documentName: 'CV',
    paperSize: 'A4',
    spelling: 'british-or-international',
    idealPages: 2,
    maxPages: 3,
    dateFormat: 'Sep 2024',
    defaultStructure: 'reverse-chronological',
    summaryLabel: 'Professional Profile',
    photo: 'common',
    personalInfo: {
      dateOfBirth: 'common',
      nationality: 'common',
      maritalStatus: 'optional',
      visaStatus: 'common',
      fullAddress: 'optional',
    },
    referencesStyle: 'on-request',
    warnings: [
      'Photo, nationality, and visa status are common in the GCC, but should be handled carefully and truthfully.',
      'Keep the CV formal and achievement-led.',
    ],
    notes: [
      'Industry, visa status, and availability can matter more than in UK or US CVs.',
      'Two to three pages is common for experienced candidates.',
    ],
  },
  'australia-nz': {
    id: 'australia-nz',
    label: 'Australia / New Zealand',
    documentName: 'Resume / CV',
    paperSize: 'A4',
    spelling: 'british',
    idealPages: 2,
    maxPages: 3,
    dateFormat: 'Sep 2024',
    defaultStructure: 'reverse-chronological',
    summaryLabel: 'Career Profile',
    photo: 'discouraged',
    personalInfo: {
      dateOfBirth: 'discouraged',
      nationality: 'discouraged',
      maritalStatus: 'discouraged',
      visaStatus: 'useful-if-relevant',
      fullAddress: 'not-required',
    },
    referencesStyle: 'available-on-request',
    warnings: [
      'Do not add a photo for most Australian or New Zealand applications.',
      'Avoid unnecessary personal details.',
      'Use British spelling conventions.',
    ],
    notes: [
      'Two to three pages can be acceptable depending on experience.',
      'Clear achievements and responsibilities are valued.',
    ],
  },
};

export const REGION_OPTIONS = Object.values(REGIONS).map(({ id, label, documentName }) => ({
  id,
  label,
  documentName,
}));

export function getRegion(regionId = 'uk-ireland') {
  return REGIONS[regionId] || REGIONS['uk-ireland'];
}
